language: python
python: "3.6"
notifications:
  email: false

env:
  global:
    - CIBW_TEST_REQUIRES="pytest"
    - CIBW_TEST_COMMAND="pytest --pyargs pybase64"
    - TWINE_USERNAME=mayeut

matrix:
  include:
    - dist: trusty
      sudo: required
      services:
        - docker
      env: PYBASE64_BUILD_WHEEL=1
    - dist: trusty
    - dist: trusty
      env: PYBASE64_TOX=1
    - dist: trusty
      env: PYBASE64_DOC=1
    - dist: trusty
      env: PYBASE64_VALGRIND=1
      addons:
        apt:
          packages:
            - valgrind
    - os: osx
      osx_image: xcode9.2
      language: generic
      env: PYBASE64_BUILD_WHEEL=1
      before_install:
        - brew update
        # Install/Upgrade OpenSSL if needed
        - brew outdated openssl || brew upgrade openssl
        # Install/Upgrade Python 3 if needed
        - brew outdated python || brew upgrade python
        # Make sure CA certificates are up-to-date
        - brew postinstall openssl
        - SSL_CERT_FILE=$(brew --prefix)/etc/openssl/cert.pem

install:
  - |
    if [ "${PYBASE64_BUILD_WHEEL:-}" != "" ]; then
      pip3 install cibuildwheel==0.7.0
    elif [ "${PYBASE64_TOX:-}" != "" ]; then
      pip install -r requirements.txt codecov
    else
      pip install -r requirements.txt
    fi

script:
  - |
    if [ "${PYBASE64_BUILD_WHEEL:-}" != "" ]; then
      cibuildwheel --output-dir todeploy
    elif [ "${PYBASE64_TOX}" != "" ]; then
      python -m tox && codecov
    elif [ "${PYBASE64_VALGRIND}" != "" ]; then
      CFLAGS="-O0" python setup.py build_ext -fiv
      PYTHONMALLOC=malloc valgrind --leak-check=full --show-leak-kinds=definite --errors-for-leak-kinds=definite --error-exitcode=2 $(pyenv which python) -m pytest
    elif [ "${PYBASE64_DOC}" != "" ]; then
      python setup.py develop
      cd docs && make html
    else
      ./travis/build-source-dist.sh
    fi
  - |
    if [ "${PYBASE64_TOX:-}${PYBASE64_VALGRIND:-}${PYBASE64_DOC:-}" == "" ]; then
      ls todeploy/
      if [ "${TRAVIS_TAG:-}" != "" ]; then
        python -m pip install twine
        python -m twine upload --skip-existing todeploy/*
      fi
    fi
