notifications:
  email: false

env:
  global:
    - CIBW_TEST_REQUIRES="nose future"
    - CIBW_TEST_COMMAND="nosetests {project}"
    - TWINE_USERNAME=mayeut

matrix:
  include:
    - dist: trusty
      sudo: required
      services:
        - docker
      env: PYBASE64_BUILD_WHEEL=1
    - dist: trusty
      language: python
      python: "3.6"
    - dist: trusty
      language: python
      python: "3.6"
      env: PYBASE64_TOX=1
    - os: osx
      osx_image: xcode8.2
      env: PYBASE64_BUILD_WHEEL=1

install:
  - if [ "${PYBASE64_BUILD_WHEEL:-}" != "" ]; then
      pip install cibuildwheel==0.4.0;
    elif [ "${PYBASE64_TOX}" != "" ]; then
      pip install -r requirements.txt codecov;
    else
      pip install -r requirements.txt;
    fi

script:
  - if [ "${PYBASE64_BUILD_WHEEL:-}" != "" ]; then
      cibuildwheel --output-dir todeploy;
    elif [ "${PYBASE64_TOX}" != "" ]; then
      python -m tox && mkdir todeploy && codecov;
    else
      ./travis/build-source-dist.sh;
    fi
  - ls todeploy/
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload todeploy/*
    fi
