language: python
python: "3.7"
notifications:
  email: false

# Don't build the depandabot branches that dependabot creates; it's redundant
# with the PR builds that Travis also does.
branches:
  except:
    - /^dependabot/

env:
  global:
    - CIBW_TEST_REQUIRES="pytest"
    - CIBW_TEST_COMMAND="pytest --pyargs pybase64"
    - CIBW_SKIP="cp27* cp34*"

matrix:
  include:
    - dist: xenial
      sudo: required
      services:
        - docker
      env: PYBASE64_BUILD_WHEEL=1
    - dist: xenial
    - dist: xenial
      env: PYBASE64_TOX=1
    - dist: xenial
      env: PYBASE64_DOC=1
    - dist: xenial
      env: PYBASE64_VALGRIND=1
      addons:
        apt:
          packages:
            - valgrind
    - os: osx
      osx_image: xcode9.4
      language: generic
      env: PYBASE64_BUILD_WHEEL=1
      before_install:
        # make sure CA certificates are up-to-date
        - brew postinstall openssl
        - SSL_CERT_FILE=$(brew --prefix)/etc/openssl/cert.pem
        # need to use a virtualenv for deployement
        - python3 -m venv venv
        - source venv/bin/activate

install:
  - |
    if [ "${PYBASE64_BUILD_WHEEL:-}" != "" ]; then
      pip install -r requirements-cibuildwheel.txt
    elif [ "${PYBASE64_TOX:-}" != "" ]; then
      pip install -r requirements.txt codecov
    elif [ "${PYBASE64_DOC:-}" != "" ]; then
      pip install -r requirements-doc.txt
    else
      pip install -r requirements.txt
    fi

script:
  - |
    if [ "${PYBASE64_BUILD_WHEEL:-}" != "" ]; then
      cibuildwheel --output-dir dist
    elif [ "${PYBASE64_TOX}" != "" ]; then
      python -m tox && codecov
    elif [ "${PYBASE64_VALGRIND}" != "" ]; then
      CFLAGS="-O0" python setup.py build_ext -fiv
      PYTHONMALLOC=malloc valgrind --leak-check=full --show-leak-kinds=definite --errors-for-leak-kinds=definite --error-exitcode=2 $(pyenv which python) -m pytest
    elif [ "${PYBASE64_DOC}" != "" ]; then
      python setup.py develop
      cd docs && make html
    else
      ./travis/build-source-dist.sh
    fi

before_deploy:
  - ls dist/

deploy:
  # Deploy on tags to GitHub Releases
  - provider: releases
    api_key:
      secure: lfOV3tIEyQOqQpcnyQryKXTHadXn6ylcJ4aQ79H64UBA3IG1DddKi5RYTHA24swr05lDPqo1uhk45clzgAT9Ftm43Y8j+UL4AunywSZV+9Gi1Vi+0ws/DhC02hgOwlt7gmxA+5gk507Xj/4bAMSfiwQ5y0fjpYP1/VRF/S744Urstn1hgSlBqr3DzFeGX1OuxWz64FeW9s9Ehb/kC2R7xvbnGj1mn4UMNjNyN4FaNNvAS5AzZ7kpnSalHPs5LEi9e5sLQK3hLeYQ5SFTy/2k+7/1qWE+O9PTlgxSP6WOGD5zv2wyzgjnSgr0xdM2yQbfq6k33P6ahlwOTHhSn4erdXKRLRgHLdYcdYuH0tFmKRUXqExjfpgyMRj2+NNgY0THZ9FKRoufmNMiByv4VxKKR4Gz0WLYbEnDsNu02AT1ta5qP3OGj+LZM0HcilPiO8kT2/V3veu9LyRzYYHtEo35Ya7WYZ9SPLm6tyAvbsR3YWzbkn9U6kmGjj0wfU1rip9mkQFMjCU7TapnzuN+D/23RZi/8apKuwSlTwxUG/lX4uwyNYhwXhv5LY+cOGSJ6E+YfOiuan3bTnsCwtDI0Y4FDnnjVZ4wp2H8PntQJ1ePR4Ei80Fjy9sVUmtQMJxMmxkYUWLlytc9Gq6MmrRD9T7FHgNIZT5WNy/0N971YcyWiYQ=
    file_glob: true
    file: "dist/*"
    skip_cleanup: true
    on:
      repo: mayeut/pybase64
      tags: true
      condition: -z "${PYBASE64_TOX:-}${PYBASE64_VALGRIND:-}${PYBASE64_DOC:-}"
  # Deploy master non-tags to test PyPI
  - provider: pypi
    server: https://test.pypi.org/legacy/
    user: __token__
    password:
      secure: Fmy8nwaENUtGLhnZTAlOS+innLmY5TPzWzQOsRirRgdOpxQ/XIabrZwVmk80+RqOkvY4okOXq43jhPmla8FZFOIo3LvkI81FcC9FHF6O93GQC5bjYdljaELCPRGxXxgp86fW5iwg5NXi6f2X7207F9RZOheuPyDIE7J0V2MJghbolIRzDC5IfHHuj3jmAMMadco571QWjLSEZ9xYlZURlhxo8IWYDU7ajSx5nFYAi0bD7Y49vjUcc4JfTsou4vVg1Y9a9hBChPZguPwss7hkh3dnFUJ1Vc10aeuhiNK/fwqKDKB4ebFMkc02aZmI6EsN5DtxTOEMhZWMrYOt4Os1xVLdvPckoBXIGz4089BoQP7GCImq/0KKHeK0NqfEIJ47A4gNc5rXmw4MIJNlwGtvceZUQy9eeyKiKXq0BuAqY3V2yozzasMbE/LV/MsosL6Qs/9W5csRdq7MJBB1y8TbrKd4UFfJ7cUovfVxhTEitPCyDMNzofpXV79L3U3I3VgXinmL2kFnSh/wf3/75lIU8FyrOpvAvPaj+sC/tXxIGy/EhrndXIelOicZDKvjm0g2cf/M7eytAUh9fkQI8pQJB5OSXP9OgheJ4kL4qBL2/yCqKdASuVH9mLNs2ZsPmdFVi4WNqLx1RvYZwYBHKzgRoVV/3s+EWXUoM1YjwPopnqo=
    distributions: clean_ext
    skip_existing: true
    skip_cleanup: true
    on:
      repo: mayeut/pybase64
      tags: false
      branch: master
      condition: -z "${PYBASE64_TOX:-}${PYBASE64_VALGRIND:-}${PYBASE64_DOC:-}"
  # Deploy on tags to PyPI
  - provider: pypi
    user: __token__
    password:
      secure: KQ/FVMKw8prgfPkna0alL6zYrNXryFGvT/Qgj05Ysp5RyuL3Uvo5ZeQfRwdNZmaHgjOgt7u3PnAbYL3eYJBIF9mpCSpaSs6NWXQwoDIt8JGaDPDqbFxWngFN0x3CxwsPsawIeMNeHQawkqRKomIqf/IBQWoGeAptfgTAXXD4u6ym7EDE0sB3a6zgdUrL3ukTB3K673LQAquxHu/BkkqOC+hj9Wp2muIGoWjW+0T8AstGsPq2+K9gi2vKxOzDKtI9opM7hl22gqyaOiEVKi40Tu97iAF/Sa0F5ODD+5AM5MzC11vBxose918Ogzcl0M6hfMRnD53yNDPEpuNyQ2aT+GA5gK6occ8lbb7K+QEoUpGGLCFUeiSdDWbtG2WplngnAPgOhHpy1/7mICn6MrPTF71HR/h1pniNoyo03Is72ujn5zvhvZoGS1wNGIwMczxO9AwcWO5cbzr5CnP15Y5dKa+QFxifO+zXGhLjG58Q6sc/1bhijy5WUiMM6NPMmGIsPj0WDOGI5CvRPLNMn3TlONrrbCxtaPnfQGbdu5QFQ6UwcpQOX9U6bKLJ5lwCc46Tt4hoZEj0hJJEKaRZ/mPsC2meYbQ3m6ErItG+KzzI7mQGuoG2zwwHjKnM3XYKuArDRv5QeR+jMFZJ0JGS8vs6c86rqe/a70K0Bvnprbfd2+M=
    distributions: clean_ext
    skip_existing: true
    skip_cleanup: true
    on:
      repo: mayeut/pybase64
      tags: true
      condition: -z "${PYBASE64_TOX:-}${PYBASE64_VALGRIND:-}${PYBASE64_DOC:-}"
