environment:
  global:
    CIBW_TEST_REQUIRES: "pytest"
    CIBW_TEST_COMMAND: "pytest --pyargs pybase64"
    CIBW_SKIP: cp27-win* cp33-win* cp34-win*
    TWINE_USERNAME: mayeut
install:
  - git submodule update --init --recursive
  - pip install -r requirements.txt cibuildwheel==0.7.0
build_script:
# Test with cp27, extension shall fail to build silently (optional)
  - python setup.py build_ext -i -f -v
# But still, tests shall pass
  - pytest
# Build wheels
  - cibuildwheel --output-dir todeploy
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    python -m twine upload --skip-existing todeploy/*.whl
    )
artifacts:
  - path: "todeploy\\*.whl"
    name: Wheels
