environment:
  global:
    CIBW_TEST_REQUIRES: "nose future"
    CIBW_TEST_COMMAND: "nosetests {project}"
    CIBW_SKIP: cp27-win*
    TWINE_USERNAME: mayeut
install:
  - git submodule update --init --recursive
build_script:
  - pip install cibuildwheel==0.4.1
  - cibuildwheel --output-dir todeploy
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    python -m twine upload todeploy/*.whl
    )
