environment:
  global:
    CIBW_TEST_REQUIRES: "nose future"
    CIBW_TEST_COMMAND: "nosetests {project}"
    CIBW_SKIP: cp27-win* cp33-win* cp34-win*
    TWINE_USERNAME: mayeut
install:
  - git submodule update --init --recursive
  - pip install -r requirements.txt cibuildwheel==0.4.1
build_script:
# Test with cp27, extension shall fail to build silently (optional)
  - python setup.py build_ext -i -f -v
# But still, tests shall pass
  - nosetests
# Create file '.cibuildwheel' so that extension build is not optional (c.f. setup.py).
  - touch .cibuildwheel
  - cibuildwheel --output-dir todeploy
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    python -m twine upload --skip-existing todeploy/*.whl
    )
