name: Linter

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build_sdist:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: python -m pip install  -r requirements-lint.txt

      - name: Run linter
        run: |
          set -exuo pipefail
          flake8 pybase64
          isort --diff --check-only pybase64
